create extension if not exists "pg_net" with schema "public" version '0.8.0';

revoke delete on table "public"."pass_schedule" from "anon";

revoke insert on table "public"."pass_schedule" from "anon";

revoke references on table "public"."pass_schedule" from "anon";

revoke select on table "public"."pass_schedule" from "anon";

revoke trigger on table "public"."pass_schedule" from "anon";

revoke truncate on table "public"."pass_schedule" from "anon";

revoke update on table "public"."pass_schedule" from "anon";

revoke delete on table "public"."pass_schedule" from "authenticated";

revoke insert on table "public"."pass_schedule" from "authenticated";

revoke references on table "public"."pass_schedule" from "authenticated";

revoke select on table "public"."pass_schedule" from "authenticated";

revoke trigger on table "public"."pass_schedule" from "authenticated";

revoke truncate on table "public"."pass_schedule" from "authenticated";

revoke update on table "public"."pass_schedule" from "authenticated";

revoke delete on table "public"."pass_schedule" from "service_role";

revoke insert on table "public"."pass_schedule" from "service_role";

revoke references on table "public"."pass_schedule" from "service_role";

revoke select on table "public"."pass_schedule" from "service_role";

revoke trigger on table "public"."pass_schedule" from "service_role";

revoke truncate on table "public"."pass_schedule" from "service_role";

revoke update on table "public"."pass_schedule" from "service_role";

alter table "public"."pass_schedule" drop constraint "pass_schedule_satellite_name_fkey";

alter table "public"."pass_schedule" drop constraint "pass_schedule_pkey";

drop index if exists "public"."pass_schedule_pkey";

drop table "public"."pass_schedule";

create table "public"."operation" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "update_at" timestamp with time zone,
    "create_user_id" uuid,
    "operators" jsonb,
    "commands" jsonb,
    "status" text,
    "results" jsonb
);


alter table "public"."operation" enable row level security;

alter table "public"."satellite_schedule" add column "operation" text;

CREATE UNIQUE INDEX operation_pkey ON public.operation USING btree (id);

alter table "public"."operation" add constraint "operation_pkey" PRIMARY KEY using index "operation_pkey";

alter table "public"."operation" add constraint "operation_create_user_id_fkey" FOREIGN KEY (create_user_id) REFERENCES auth.users(id) ON UPDATE CASCADE ON DELETE RESTRICT not valid;

alter table "public"."operation" validate constraint "operation_create_user_id_fkey";

grant delete on table "public"."operation" to "anon";

grant insert on table "public"."operation" to "anon";

grant references on table "public"."operation" to "anon";

grant select on table "public"."operation" to "anon";

grant trigger on table "public"."operation" to "anon";

grant truncate on table "public"."operation" to "anon";

grant update on table "public"."operation" to "anon";

grant delete on table "public"."operation" to "authenticated";

grant insert on table "public"."operation" to "authenticated";

grant references on table "public"."operation" to "authenticated";

grant select on table "public"."operation" to "authenticated";

grant trigger on table "public"."operation" to "authenticated";

grant truncate on table "public"."operation" to "authenticated";

grant update on table "public"."operation" to "authenticated";

grant delete on table "public"."operation" to "service_role";

grant insert on table "public"."operation" to "service_role";

grant references on table "public"."operation" to "service_role";

grant select on table "public"."operation" to "service_role";

grant trigger on table "public"."operation" to "service_role";

grant truncate on table "public"."operation" to "service_role";

grant update on table "public"."operation" to "service_role";


